import {
	RemixiconComponentType,
	RiBookLine,
	RiCarLine,
	RiFirefoxFill,
	RiFireLine,
	RiFirstAidKitLine,
	RiFridgeLine,
	RiHome8Line,
	RiHomeOfficeLine,
	RiHomeWifiLine,
	RiKeyboardLine,
	RiKnifeLine,
	RiTShirtAirLine,
	RiSunLine,
	RiSurroundSoundLine,
	RiTvLine,
	RiVideoLine,
	RiVidiconLine,
	RiWaterFlashLine,
	RiWheelchairLine,
	RiWifiLine,
	RiZcoolLine,
} from "@remixicon/react"

import { AirConditioner, Bath, Dumbells, Gamepad, Swimming } from "@/assets/svg"
import { AmenitiesIconName } from "@/types"

export const icons: Record<
	AmenitiesIconName,
	React.FC<React.SVGProps<SVGSVGElement>> | RemixiconComponentType
> = {
	"Air conditioning": AirConditioner,
	"beach-access": RiHome8Line,
	"bbq-grill": RiKnifeLine,
	"dedicated-kitchen": RiFirefoxFill,
	"fire-alarm": RiFireLine,
	"fire-extinguisher": RiFireLine,
	"fire-pit": RiFireLine,
	"first-aid-kit": RiFirstAidKitLine,
	"gas-cooker": RiWaterFlashLine,
	"Fitness center": Dumbells,
	"handicap-accessible": RiWheelchairLine,
	jacuzzi: Bath,
	"lake-access": RiWaterFlashLine,
	Library: RiBookLine,
	"parking-space": RiCarLine,
	patio: RiHomeWifiLine,
	piano: RiKeyboardLine,
	"ps5-console": Gamepad,
	"Mini refrigerator": RiFridgeLine,
	"security-system": RiVidiconLine,
	"smoke-alarm": RiZcoolLine,
	"snooker-table": RiHome8Line,
	"sound-system": RiSurroundSoundLine,
	"swimming-pool": Swimming,
	"streaming-services": RiVideoLine,
	television: RiTvLine,
	"washing-machine": RiTShirtAirLine,
	"water-heater": RiSunLine,
	"Wi-Fi": RiWifiLine,
	workspace: RiHomeOfficeLine,
}

export const amenities_list = [
	"Air conditioning",
	"beach-access",
	"bbq-grill",
	"dedicated-kitchen",
	"fire-alarm",
	"fire-extinguisher",
	"fire-pit",
	"first-aid-kit",
	"gas-cooker",
	"Fitness center",
	"handicap-accessible",
	"jacuzzi",
	"lake-access",
	"Library",
	"parking-space",
	"patio",
	"piano",
	"ps5-console",
	"Mini refrigerator",
	"security-system",
	"smoke-alarm",
	"snooker-table",
	"sound-system",
	"swimming-pool",
	"streaming-services",
	"television",
	"washing-machine",
	"water-heater",
	"Wi-Fi",
	"workspace",
] as const

export const yup_amenities_list = [
	"Air conditioning",
	"beach-access",
	"bbq-grill",
	"dedicated-kitchen",
	"fire-alarm",
	"fire-extinguisher",
	"fire-pit",
	"first-aid-kit",
	"gas-cooker",
	"Fitness center",
	"handicap-accessible",
	"jacuzzi",
	"lake-access",
	"Library",
	"parking-space",
	"patio",
	"piano",
	"ps5-console",
	"Mini refrigerator",
	"security-system",
	"smoke-alarm",
	"snooker-table",
	"sound-system",
	"swimming-pool",
	"streaming-services",
	"television",
	"washing-machine",
	"water-heater",
	"Wi-Fi",
	"workspace",
]
