export const states = [
	{ label: "Abia", value: "abia" },
	{ label: "Abuja", value: "abuja" },
	{ label: "Adamawa", value: "adamawa" },
	{ label: "Akwa-Ibom", value: "akwa-ibom" },
	{ label: "Anambra", value: "anambra" },
	{ label: "Bauchi", value: "bauchi" },
	{ label: "Bayelsa", value: "bayelsa" },
	{ label: "Benue", value: "benue" },
	{ label: "Borno", value: "borno" },
	{ label: "Cross River", value: "cross river" },
	{ label: "Delta", value: "delta" },
	{ label: "Ebonyi", value: "ebonyi" },
	{ label: "Edo", value: "edo" },
	{ label: "Ekiti", value: "ekiti" },
	{ label: "Enugu", value: "enugu" },
	{ label: "Gombe", value: "gombe" },
	{ label: "Imo", value: "imo" },
	{ label: "Jigawa", value: "jigawa" },
	{ label: "Kaduna", value: "kaduna" },
	{ label: "Kano", value: "kano" },
	{ label: "Katsina", value: "katsina" },
	{ label: "Kebbi", value: "kebii" },
	{ label: "Kogi", value: "kogi" },
	{ label: "Kwara", value: "kwara" },
	{ label: "Lagos", value: "lagos" },
	{ label: "Nasarawa", value: "nasarawa" },
	{ label: "Niger", value: "niger" },
	{ label: "Ogun", value: "ogun" },
	{ label: "Ondo", value: "ondo" },
	{ label: "Osun", value: "osun" },
	{ label: "Oyo", value: "oyo" },
	{ label: "Plateau", value: "plateau" },
	{ label: "Rivers", value: "rivers" },
	{ label: "Sokoto", value: "sokoto" },
	{ label: "Taraba", value: "taraba" },
	{ label: "Yobe", value: "yobe" },
	{ label: "Zamfara", value: "zamfara" },
]

export const only_places = [
	"Surulere, Lagos",
	"Ikeja, Lagos",
	"Lekki, Lagos",
	"Ikoyi, Lagos",
	"Magodo, Lagos",
	"Victoria Island, Lagos",
	"Lagos Island, Lagos",
	"Ajah, Lagos",
	"Ojo, Lagos",
	"Ojota, Lagos",
	"Ogudu, Lagos",
	"Epe, Lagos",
	"Ikorodu, Lagos",
	"Maryland, Lagos",
	"Gbagada, Lagos",
	"Apapa, Lagos",
	"Oshodi, Lagos",
	"Yaba, Lagos",
	"Agege, Lagos",
	"Festac, Lagos",
	"Ogba, Lagos",
	"Ibadan, Oyo",
	"Ogbomosho, Oyo",
	"Port Harcourt, Rivers",
	"Wuse II, FCT",
]
export const places = [
	{ label: "All", value: "all" },
	{ label: "Surulere", value: "surulere" },
	{ label: "Ikeja", value: "ikeja" },
	{ label: "Lekki", value: "lekki" },
	{ label: "Ikoyi", value: "ikoyi" },
	{ label: "Magodo", value: "magodo" },
	{ label: "Victoria Island", value: "victoria island" },
	{ label: "Lagos Island", value: "lagos island" },
	{ label: "Ajah", value: "ajah" },
	{ label: "Ojo", value: "ojo" },
	{ label: "Ojota", value: "ojota" },
	{ label: "Ogudu", value: "ogudu" },
	{ label: "Epe", value: "epe" },
	{ label: "Ikorodu", value: "ikorodu" },
	{ label: "Maryland", value: "maryland" },
	{ label: "Gbagada", value: "gbagada" },
	{ label: "Apapa", value: "apapa" },
	{ label: "Oshodi", value: "oshodi" },
	{ label: "Yaba", value: "yaba" },
	{ label: "Agege", value: "agege" },
	{ label: "Festac", value: "festac" },
	{ label: "Ogba", value: "ogba" },
	{ label: "Ibadan", value: "ibadan" },
	{ label: "Ogbomosho", value: "ogbomosho" },
	{ label: "Oyo Town", value: "oyo town" },
	{ label: "Owo", value: "owo" },
	{ label: "Port Harcourt", value: "port harcourt" },
	{ label: "Abuja", value: "abuja" },
	{ label: "Gwagwalada", value: "gwagwalada" },
	{ label: "Wuse II", value: "wuse ii" },
	{ label: "Sokoto", value: "sokoto" },
	{ label: "Yenagoa", value: "yenagoa" },
	{ label: "Yola", value: "yola" },
	{ label: "Zaria", value: "zaria" },
]
