name: build-check

on:
 pull_request:
  branches:
   - main
   - staging

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: check-out
     uses: actions/checkout@v3

   - name: set-up-node
     uses: actions/setup-node@v2
     with:
      node-version: 20

   - name: install-deps
     run: npm install

   - name: check code
     run: npm run check-code

   - name: build
     run: npm run build
